/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    brands: Brand;
    clients: Client;
    inquiries: Inquiry;
    'experience-briefs': ExperienceBrief;
    experiences: Experience;
    'vendor-partners': VendorPartner;
    venues: Venue;
    'package-options': PackageOption;
    events: Event;
    proposals: Proposal;
    tasks: Task;
    'menu-concepts': MenuConcept;
    recipes: Recipe;
    menus: Menu;
    'dietary-notes': DietaryNote;
    testimonials: Testimonial;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'experience-briefs': ExperienceBriefsSelect<false> | ExperienceBriefsSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    'vendor-partners': VendorPartnersSelect<false> | VendorPartnersSelect<true>;
    venues: VenuesSelect<false> | VenuesSelect<true>;
    'package-options': PackageOptionsSelect<false> | PackageOptionsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    proposals: ProposalsSelect<false> | ProposalsSelect<true>;
    tasks: TasksSelect<false> | TasksSelect<true>;
    'menu-concepts': MenuConceptsSelect<false> | MenuConceptsSelect<true>;
    recipes: RecipesSelect<false> | RecipesSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    'dietary-notes': DietaryNotesSelect<false> | DietaryNotesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  fullName?: string | null;
  role?:
    | ('admin' | 'hospitalityDirector' | 'experienceCurator' | 'culinaryTeam' | 'vendorPartner' | 'client' | 'team')
    | null;
  profilePhoto?: (string | null) | Media;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  mediaType?: ('food' | 'venue' | 'experience' | 'tablescape' | 'wine' | 'luxuryLifestyle' | 'brand' | 'video') | null;
  photographerCredit?: string | null;
  featured?: boolean | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: string;
  brandName: string;
  /**
   * Used for white-label routing and brand instance control.
   */
  brandSlug: string;
  brandType?:
    ('hospitalityBrand' | 'privateChef' | 'winery' | 'hotelResort' | 'eventCompany' | 'conciergeCompany') | null;
  status?: ('setup' | 'active' | 'paused' | 'archived') | null;
  primaryMarket?: string | null;
  website?: string | null;
  /**
   * Short brand positioning used across proposals and client-facing experiences.
   */
  publicPositioning?: string | null;
  logo?: (string | null) | Media;
  brandColors?:
    | {
        label?: string | null;
        hex?: string | null;
        id?: string | null;
      }[]
    | null;
  systemSettings?: {
    /**
     * Target profit margin percentage for generated packages.
     */
    defaultMarginTarget?: number | null;
    minimumDepositPercent?: number | null;
    whiteLabelEnabled?: boolean | null;
  };
  brandNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: string;
  /**
   * Which hospitality brand or white-label instance this client belongs to.
   */
  brand?: (string | null) | Brand;
  fullName: string;
  email: string;
  phone?: string | null;
  instagram?: string | null;
  clientType?: ('private' | 'realtor' | 'executive' | 'partner' | 'hospitalityBrand' | 'whiteLabelPartner') | null;
  vipStatus?: ('standard' | 'preferred' | 'vip' | 'foundingPartner') | null;
  preferredExperienceStyle?:
    | (
        | 'privateDinner'
        | 'estateDinner'
        | 'wineCountry'
        | 'executiveHospitality'
        | 'realtorConcierge'
        | 'celebration'
        | 'luxuryEvent'
        | 'clubLounge'
      )[]
    | null;
  favoriteVendors?: (string | VendorPartner)[] | null;
  favoriteVenues?: (string | Venue)[] | null;
  averageSpendRange?: string | null;
  /**
   * Private relationship notes, preferences, emotional context, luxury expectations, and follow-up details.
   */
  relationshipNotes?: string | null;
  internalStrategyNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-partners".
 */
export interface VendorPartner {
  id: string;
  businessName: string;
  vendorType:
    | 'venue'
    | 'winery'
    | 'dj'
    | 'liveMusic'
    | 'iceCarver'
    | 'florist'
    | 'photographer'
    | 'videographer'
    | 'rentalCompany'
    | 'transportation'
    | 'hotel'
    | 'countryClub'
    | 'privateEstate'
    | 'bartending'
    | 'security'
    | 'luxuryConcierge'
    | 'lightingDesign'
    | 'tablescapeRentals'
    | 'privateChef'
    | 'clubLounge';
  contactName?: string | null;
  email?: string | null;
  phone?: string | null;
  website?: string | null;
  instagram?: string | null;
  serviceRegion?: string | null;
  pricingTier?: ('accessible' | 'premium' | 'luxury' | 'ultraLuxury') | null;
  preferredPartner?: boolean | null;
  /**
   * Approved for white-label KXD hospitality deployment.
   */
  whiteLabelApproved?: boolean | null;
  averageSpendRange?: string | null;
  operationalNotes?: string | null;
  /**
   * Internal notes about aesthetic quality, professionalism, guest experience, and overall fit.
   */
  luxuryFitNotes?: string | null;
  gallery?: (string | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues".
 */
export interface Venue {
  id: string;
  venueName: string;
  venueType:
    | 'winery'
    | 'privateEstate'
    | 'countryClub'
    | 'luxuryHome'
    | 'hotel'
    | 'resort'
    | 'outdoorScenic'
    | 'restaurantPartner'
    | 'clubLounge';
  region?: string | null;
  address?: string | null;
  website?: string | null;
  instagram?: string | null;
  contactName?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  guestCapacity?: number | null;
  pricingTier?: ('premium' | 'luxury' | 'ultraLuxury') | null;
  featured?: boolean | null;
  whiteLabelReady?: boolean | null;
  venueFeatures?:
    | (
        | 'winePairing'
        | 'scenicViews'
        | 'indoorOutdoor'
        | 'chefKitchen'
        | 'luxuryLodging'
        | 'liveMusic'
        | 'weddingFriendly'
        | 'corporateReady'
        | 'luxuryEventReady'
        | 'clubAtmosphere'
      )[]
    | null;
  preferredVendorPartners?: (string | VendorPartner)[] | null;
  internalHospitalityNotes?: string | null;
  /**
   * Internal notes about atmosphere, aesthetics, service quality, emotional feel, and overall experience alignment.
   */
  luxuryExperienceNotes?: string | null;
  gallery?: (string | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: string;
  /**
   * Which hospitality brand or white-label instance this inquiry belongs to.
   */
  brand?: (string | null) | Brand;
  /**
   * The public channel or campaign that originated this inquiry.
   */
  leadSource?:
    | (
        | 'website'
        | 'concierge'
        | 'packages'
        | 'partner-concierge'
        | 'community-partnership'
        | 'realtor'
        | 'wine-country'
        | 'referral'
      )
    | null;
  eventTitle: string;
  client: string | Client;
  status?:
    | (
        | 'newLead'
        | 'discoveryNeeded'
        | 'discoveryScheduled'
        | 'briefInProgress'
        | 'packageInProgress'
        | 'proposalInProgress'
        | 'proposalSent'
        | 'approved'
        | 'closed'
      )
    | null;
  eventDate?: string | null;
  guestCount?: number | null;
  locationType?:
    ('privateHome' | 'estate' | 'winery' | 'venue' | 'countryClub' | 'hotel' | 'clubLounge' | 'undecided') | null;
  preferredRegion?: string | null;
  /**
   * Capture the dream version of the experience. Mood, setting, food, music, atmosphere, and emotional goal.
   */
  experienceVision: string;
  occasion?:
    | (
        | 'privateDinner'
        | 'birthday'
        | 'anniversary'
        | 'proposalEngagement'
        | 'weddingWeekend'
        | 'corporateExecutive'
        | 'realtorHospitality'
        | 'wineCountryExperience'
        | 'customCelebration'
        | 'whiteLabelHospitality'
      )
    | null;
  budgetRange?: ('1-3k' | '3-5k' | '5-10k' | '10-25k' | '25kPlus') | null;
  desiredAddOns?:
    | (
        | 'venueSourcing'
        | 'wineryPartnership'
        | 'dj'
        | 'liveMusic'
        | 'iceCarving'
        | 'florals'
        | 'photography'
        | 'videography'
        | 'luxuryTransportation'
        | 'bartending'
        | 'rentalsTablescape'
        | 'lightingDesign'
        | 'hotelLodging'
      )[]
    | null;
  dietaryNotes?: string | null;
  priorityLevel?: ('standard' | 'highTouch' | 'vip') | null;
  /**
   * Marks whether this inquiry has been turned into an Experience Brief.
   */
  briefGenerated?: boolean | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-briefs".
 */
export interface ExperienceBrief {
  id: string;
  briefTitle: string;
  client: string | Client;
  inquiry?: (string | null) | Inquiry;
  status?: ('draft' | 'readyForPackage' | 'packageBuilt' | 'proposalReady') | null;
  packageReadiness?:
    ('needsReview' | 'ready' | 'needsVenueMatch' | 'needsVendorMatch' | 'needsCulinaryDirection') | null;
  experienceType?:
    | (
        | 'privateDinner'
        | 'estateDinner'
        | 'wineCountryExperience'
        | 'executiveHospitality'
        | 'realtorConcierge'
        | 'luxuryCelebration'
        | 'whiteLabelHospitality'
      )
    | null;
  experienceMood?:
    | (
        | 'warmIntimate'
        | 'elegantRefined'
        | 'darkCinematic'
        | 'wineCountryRelaxed'
        | 'modernLuxury'
        | 'celebratory'
        | 'highEnergy'
        | 'quietlyPremium'
      )[]
    | null;
  /**
   * The client’s ideal version of the event. Capture the emotional, visual, culinary, and hospitality vision.
   */
  dreamExperience?: string | null;
  cuisineDirection?: string | null;
  serviceStyle?:
    | (
        | 'coursedDinner'
        | 'familyStyle'
        | 'tastingMenu'
        | 'cocktailReception'
        | 'interactiveStations'
        | 'fullExperienceBuildout'
      )
    | null;
  dietaryRestrictions?: (string | DietaryNote)[] | null;
  preferredVenueTypes?:
    ('estate' | 'winery' | 'privateResidence' | 'hotel' | 'countryClub' | 'outdoorScenic' | 'clubLounge')[] | null;
  desiredEnhancements?:
    | (
        | 'winePairing'
        | 'liveMusic'
        | 'dj'
        | 'florals'
        | 'iceCarving'
        | 'luxuryTransport'
        | 'photography'
        | 'videography'
        | 'lightingDesign'
        | 'luxuryRentals'
        | 'hotelLodging'
      )[]
    | null;
  matchedVenues?: (string | Venue)[] | null;
  matchedVendors?: (string | VendorPartner)[] | null;
  /**
   * Describe how the client wants guests to feel during and after the experience.
   */
  emotionalOutcome?: string | null;
  /**
   * Internal notes on how to package, price, position, and protect margin.
   */
  internalStrategy?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dietary-notes".
 */
export interface DietaryNote {
  id: string;
  guestName: string;
  client?: (string | null) | Client;
  restrictionType?:
    | (
        | 'glutenFree'
        | 'dairyFree'
        | 'nutAllergy'
        | 'shellfishAllergy'
        | 'vegetarian'
        | 'vegan'
        | 'pescatarian'
        | 'kosher'
        | 'halal'
        | 'noPork'
        | 'noAlcohol'
      )[]
    | null;
  severity?: ('preference' | 'sensitivity' | 'severeAllergy') | null;
  favoriteIngredients?: string | null;
  ingredientsToAvoid?: string | null;
  /**
   * Capture refined tastes, favorite wines, premium ingredients, dislikes, and guest expectations.
   */
  luxuryPreferenceNotes?: string | null;
  specialNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: string;
  /**
   * The hospitality brand or white-label instance this experience belongs to.
   */
  brand: string | Brand;
  title: string;
  status?:
    | (
        | 'lead'
        | 'discovery'
        | 'experienceDesign'
        | 'packageBuilding'
        | 'proposalSent'
        | 'booked'
        | 'inProduction'
        | 'completed'
        | 'archived'
      )
    | null;
  experienceType:
    | 'privateDinner'
    | 'estateExperience'
    | 'wineryEvent'
    | 'luxuryPicnic'
    | 'hotelResortExperience'
    | 'countryClubExperience'
    | 'clubLoungeExperience'
    | 'corporateHospitality'
    | 'retreat'
    | 'custom';
  client: string | Client;
  eventDate?: string | null;
  guestCount?: number | null;
  budgetRange?: ('1kTo5k' | '5kTo10k' | '10kTo25k' | '25kTo50k' | '50kPlus') | null;
  /**
   * The memorable experience the client is imagining in their own words.
   */
  clientDream?: string | null;
  /**
   * How the client wants guests to feel during and after the experience.
   */
  emotionalOutcome?: string | null;
  styleDirection?:
    | (
        | 'cinematic'
        | 'warmIntimate'
        | 'modernLuxury'
        | 'wineCountry'
        | 'darkMoody'
        | 'highEnergy'
        | 'romantic'
        | 'executive'
        | 'familyCentered'
      )[]
    | null;
  locationPreferences?: {
    preferredCity?: string | null;
    preferredRegion?: string | null;
    radiusMiles?: number | null;
    locationNotes?: string | null;
  };
  venue?: (string | null) | Venue;
  vendors?: (string | VendorPartner)[] | null;
  menuConcept?: (string | null) | MenuConcept;
  packageOptions?: (string | PackageOption)[] | null;
  proposal?: (string | null) | Proposal;
  event?: (string | null) | Event;
  profitGuardrails?: {
    targetMargin?: number | null;
    minimumMargin?: number | null;
    estimatedBudget?: number | null;
    internalCostCap?: number | null;
  };
  /**
   * Internal notes for automation logic, package generation, and future AI matching.
   */
  systemNotes?: string | null;
  vision?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-concepts".
 */
export interface MenuConcept {
  id: string;
  menuTitle: string;
  cuisineStyle?:
    | (
        | 'modernAmerican'
        | 'italian'
        | 'french'
        | 'japanese'
        | 'mediterranean'
        | 'wineCountrySeasonal'
        | 'pacificNorthwest'
        | 'farmToTable'
        | 'customClientDirection'
      )[]
    | null;
  serviceStyle?:
    | (
        | 'coursedDinner'
        | 'familyStyle'
        | 'tastingMenu'
        | 'cocktailReception'
        | 'interactiveStations'
        | 'fullHospitalityExperience'
      )
    | null;
  sampleCourses?:
    | {
        courseName?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Memorable culinary moments, chef interactions, tableside elements, or surprise details.
   */
  signatureMoments?:
    | {
        momentTitle?: string | null;
        momentDescription?: string | null;
        id?: string | null;
      }[]
    | null;
  winePairingNotes?: string | null;
  seasonality?: ('spring' | 'summer' | 'fall' | 'winter' | 'yearRound')[] | null;
  estimatedFoodCost?: number | null;
  suggestedClientPrice?: number | null;
  luxuryTier?: ('premium' | 'luxury' | 'ultraLuxury') | null;
  chefNotes?: string | null;
  internalMarginNotes?: string | null;
  gallery?: (string | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "package-options".
 */
export interface PackageOption {
  id: string;
  packageName: string;
  client?: (string | null) | Client;
  experienceBrief?: (string | null) | ExperienceBrief;
  status?: ('draft' | 'internalReview' | 'sentToClient' | 'approved' | 'declined') | null;
  includedVendors?: (string | VendorPartner)[] | null;
  selectedVenue?: (string | null) | Venue;
  menuConcept?: (string | null) | MenuConcept;
  clientPrice: number;
  foodCost?: number | null;
  vendorCost?: number | null;
  laborCost?: number | null;
  travelCost?: number | null;
  rentalCost?: number | null;
  /**
   * Automatically calculated total internal cost.
   */
  totalEstimatedCost?: number | null;
  /**
   * Automatically calculated projected profit.
   */
  estimatedProfit?: number | null;
  /**
   * Automatically calculated profit percentage.
   */
  profitMargin?: number | null;
  marginStatus?: ('review' | 'healthy' | 'premium' | 'thin') | null;
  experienceSummary?: string | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposals".
 */
export interface Proposal {
  id: string;
  proposalTitle: string;
  client: string | Client;
  event?: (string | null) | Event;
  experienceBrief?: (string | null) | ExperienceBrief;
  packageOption?: (string | null) | PackageOption;
  proposalStatus?:
    ('draft' | 'internalReview' | 'sent' | 'viewed' | 'approved' | 'depositPaid' | 'booked' | 'declined') | null;
  proposalSummary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  experienceVision?: string | null;
  includedExperiences?:
    | {
        experienceItem?: string | null;
        id?: string | null;
      }[]
    | null;
  includedVendors?: (string | VendorPartner)[] | null;
  venue?: (string | null) | Venue;
  menuConcept?: (string | null) | MenuConcept;
  guestCount?: number | null;
  eventDate?: string | null;
  totalInvestment: number;
  /**
   * Automatically defaults to 50% if left empty.
   */
  depositRequired?: number | null;
  finalBalance?: number | null;
  internalProjectedProfit?: number | null;
  proposalPdf?: (string | null) | Media;
  signatureReceived?: boolean | null;
  depositPaid?: boolean | null;
  clientFeedback?: string | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  eventName: string;
  client: string | Client;
  packageOption?: (string | null) | PackageOption;
  venue?: (string | null) | Venue;
  eventDate: string;
  guestCount?: number | null;
  eventStatus?: ('planning' | 'confirmed' | 'vendorCoordination' | 'inProduction' | 'completed' | 'archived') | null;
  assignedVendors?: (string | VendorPartner)[] | null;
  timelineNotes?: string | null;
  staffNotes?: string | null;
  clientNotes?: string | null;
  arrivalInstructions?: string | null;
  /**
   * Memorable moments, surprise elements, guest highlights, and emotional touchpoints.
   */
  specialMoments?: string | null;
  gallery?: (string | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: string;
  brand: string | Brand;
  taskTitle: string;
  status?: ('open' | 'inProgress' | 'waiting' | 'blocked' | 'complete') | null;
  priority?: ('low' | 'normal' | 'high' | 'critical') | null;
  taskType?:
    | (
        | 'discoveryCall'
        | 'clientFollowUp'
        | 'venueResearch'
        | 'venueOutreach'
        | 'vendorSourcing'
        | 'vendorOutreach'
        | 'menuDevelopment'
        | 'experienceDesign'
        | 'packageBuilding'
        | 'proposalPrep'
        | 'depositCollection'
        | 'eventPrep'
        | 'dayOfCoordination'
        | 'postEventFollowUp'
        | 'testimonialRequest'
        | 'automationReview'
      )
    | null;
  relatedClient?: (string | null) | Client;
  relatedInquiry?: (string | null) | Inquiry;
  relatedExperience?: (string | null) | Experience;
  relatedEvent?: (string | null) | Event;
  assignedTo?: (string | null) | User;
  dueDate?: string | null;
  /**
   * Marks whether this task can later be automated by the system.
   */
  automationEligible?: boolean | null;
  generatedBySystem?: boolean | null;
  estimatedRevenueImpact?: number | null;
  notes?: string | null;
  internalOperationsNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Private recipe library. Use visibility to mark menu-ready or publishing-candidate recipes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes".
 */
export interface Recipe {
  id: string;
  name: string;
  shortDescription?: string | null;
  category?:
    | (
        | 'appetizer'
        | 'soup'
        | 'salad'
        | 'firstCourse'
        | 'main'
        | 'side'
        | 'dessert'
        | 'beverage'
        | 'amuse'
        | 'bread'
        | 'sauce'
        | 'other'
      )
    | null;
  cuisine?:
    | (
        | 'modernAmerican'
        | 'italian'
        | 'french'
        | 'japanese'
        | 'mediterranean'
        | 'wineCountrySeasonal'
        | 'pacificNorthwest'
        | 'farmToTable'
        | 'custom'
      )
    | null;
  course?: ('welcome' | 'appetizer' | 'first' | 'main' | 'side' | 'dessert' | 'beverage' | 'other') | null;
  dietaryTags?:
    ('vegetarian' | 'vegan' | 'pescatarian' | 'glutenFree' | 'dairyFree' | 'nutFree' | 'halal' | 'kosher')[] | null;
  allergenTags?:
    | (
        | 'gluten'
        | 'dairy'
        | 'eggs'
        | 'treeNuts'
        | 'peanuts'
        | 'shellfish'
        | 'fish'
        | 'soy'
        | 'sesame'
        | 'pork'
        | 'alcohol'
      )[]
    | null;
  yieldQuantity?: number | null;
  yieldUnit?: ('servings' | 'portions' | 'pieces' | 'batch') | null;
  prepTimeMinutes?: number | null;
  cookTimeMinutes?: number | null;
  ingredients?:
    | {
        quantity?: string | null;
        unit?: string | null;
        ingredient: string;
        preparationNote?: string | null;
        id?: string | null;
      }[]
    | null;
  steps?:
    | {
        instruction: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Internal culinary notes — never shown on client menus.
   */
  chefNotes?: string | null;
  platingNotes?: string | null;
  /**
   * Storage or make-ahead guidance.
   */
  storageNotes?: string | null;
  /**
   * Director-only cost notes. Hidden from non-directors.
   */
  internalCostNotes?: string | null;
  featuredImage?: (string | null) | Media;
  status: 'draft' | 'tested' | 'approved' | 'archived';
  /**
   * Private by default. Menu-ready recipes appear in the menu builder picker. Publishing candidates are reserved for a future cookbook/subscription.
   */
  visibility: 'private' | 'menuReady' | 'publishingCandidate';
  /**
   * Optional slug for a future public cookbook entry.
   */
  slug?: string | null;
  publicTitle?: string | null;
  publicSummary?: string | null;
  heroImage?: (string | null) | Media;
  /**
   * Optional story or chef introduction for publishing.
   */
  chefIntroduction?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Client menu builder. Internal notes and review tokens never appear on the client review page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: string;
  /**
   * Operator-facing name — not shown to clients.
   */
  internalName: string;
  client: string | Client;
  inquiry?: (string | null) | Inquiry;
  event?: (string | null) | Event;
  /**
   * Client-facing occasion or event title.
   */
  occasionTitle: string;
  serviceDate?: string | null;
  guestCount?: number | null;
  /**
   * Client-visible opening note on the menu presentation.
   */
  introductoryMessage?: string | null;
  sections?:
    | {
        sectionName: string;
        items?:
          | {
              /**
               * Optional link to a saved recipe. Client wording below is independent.
               */
              recipe?: (string | null) | Recipe;
              clientTitle: string;
              clientDescription?: string | null;
              /**
               * Show dietary / allergen labels on the client menu.
               */
              showDietary?: boolean | null;
              /**
               * Client-facing dietary labels (comma-separated).
               */
              dietaryDisplay?: string | null;
              /**
               * Client-facing allergen labels (comma-separated).
               */
              allergenDisplay?: string | null;
              /**
               * Never shown on client review.
               */
              internalItemNotes?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional client-facing pricing language (e.g. investment note). Do not include cost or margin data.
   */
  pricingPresentation?: string | null;
  /**
   * Optional client-visible investment figure. Follows established proposal-style presentation only — never show food cost or margin.
   */
  displayInvestment?: number | null;
  /**
   * Operator notes — never appear on client review.
   */
  internalNotes?: string | null;
  status: 'draft' | 'readyForReview' | 'sent' | 'revisionRequested' | 'approved' | 'archived';
  /**
   * Incremented when a revision snapshot is recorded.
   */
  version?: number | null;
  sentAt?: string | null;
  approvedAt?: string | null;
  /**
   * Bounded snapshots of client-facing menu content.
   */
  revisionHistory?:
    | {
        version: number;
        snapshotAt: string;
        reason?: string | null;
        /**
         * JSON snapshot of client-visible menu fields.
         */
        snapshotJson: string;
        id?: string | null;
      }[]
    | null;
  /**
   * SHA-256 hash of the opaque review token. Plaintext is never stored.
   */
  reviewTokenHash?: string | null;
  reviewTokenExpiresAt?: string | null;
  reviewTokenRevokedAt?: string | null;
  reviewTokenCreatedAt?: string | null;
  /**
   * Bounded structured client review history.
   */
  reviews?:
    | {
        action: 'approve' | 'requestRevision';
        comment?: string | null;
        submittedAt: string;
        menuVersion?: number | null;
        /**
         * Truncated client key for abuse diagnostics — not PII.
         */
        clientKeyHint?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  clientName: string;
  experienceType?:
    | (
        | 'privateDinner'
        | 'estateEvent'
        | 'wineCountry'
        | 'executiveHospitality'
        | 'luxuryCelebration'
        | 'whiteLabelHospitality'
      )
    | null;
  testimonial: string;
  rating?: number | null;
  featured?: boolean | null;
  featuredQuote?: string | null;
  eventGallery?: (string | Media)[] | null;
  clientPhoto?: (string | null) | Media;
  venue?: (string | null) | Venue;
  location?: string | null;
  /**
   * Internal notes about the overall emotional impact and hospitality quality.
   */
  luxuryExperienceNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'brands';
        value: string | Brand;
      } | null)
    | ({
        relationTo: 'clients';
        value: string | Client;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: string | Inquiry;
      } | null)
    | ({
        relationTo: 'experience-briefs';
        value: string | ExperienceBrief;
      } | null)
    | ({
        relationTo: 'experiences';
        value: string | Experience;
      } | null)
    | ({
        relationTo: 'vendor-partners';
        value: string | VendorPartner;
      } | null)
    | ({
        relationTo: 'venues';
        value: string | Venue;
      } | null)
    | ({
        relationTo: 'package-options';
        value: string | PackageOption;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'proposals';
        value: string | Proposal;
      } | null)
    | ({
        relationTo: 'tasks';
        value: string | Task;
      } | null)
    | ({
        relationTo: 'menu-concepts';
        value: string | MenuConcept;
      } | null)
    | ({
        relationTo: 'recipes';
        value: string | Recipe;
      } | null)
    | ({
        relationTo: 'menus';
        value: string | Menu;
      } | null)
    | ({
        relationTo: 'dietary-notes';
        value: string | DietaryNote;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullName?: T;
  role?: T;
  profilePhoto?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  mediaType?: T;
  photographerCredit?: T;
  featured?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  brandName?: T;
  brandSlug?: T;
  brandType?: T;
  status?: T;
  primaryMarket?: T;
  website?: T;
  publicPositioning?: T;
  logo?: T;
  brandColors?:
    | T
    | {
        label?: T;
        hex?: T;
        id?: T;
      };
  systemSettings?:
    | T
    | {
        defaultMarginTarget?: T;
        minimumDepositPercent?: T;
        whiteLabelEnabled?: T;
      };
  brandNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  brand?: T;
  fullName?: T;
  email?: T;
  phone?: T;
  instagram?: T;
  clientType?: T;
  vipStatus?: T;
  preferredExperienceStyle?: T;
  favoriteVendors?: T;
  favoriteVenues?: T;
  averageSpendRange?: T;
  relationshipNotes?: T;
  internalStrategyNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  brand?: T;
  leadSource?: T;
  eventTitle?: T;
  client?: T;
  status?: T;
  eventDate?: T;
  guestCount?: T;
  locationType?: T;
  preferredRegion?: T;
  experienceVision?: T;
  occasion?: T;
  budgetRange?: T;
  desiredAddOns?: T;
  dietaryNotes?: T;
  priorityLevel?: T;
  briefGenerated?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-briefs_select".
 */
export interface ExperienceBriefsSelect<T extends boolean = true> {
  briefTitle?: T;
  client?: T;
  inquiry?: T;
  status?: T;
  packageReadiness?: T;
  experienceType?: T;
  experienceMood?: T;
  dreamExperience?: T;
  cuisineDirection?: T;
  serviceStyle?: T;
  dietaryRestrictions?: T;
  preferredVenueTypes?: T;
  desiredEnhancements?: T;
  matchedVenues?: T;
  matchedVendors?: T;
  emotionalOutcome?: T;
  internalStrategy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  brand?: T;
  title?: T;
  status?: T;
  experienceType?: T;
  client?: T;
  eventDate?: T;
  guestCount?: T;
  budgetRange?: T;
  clientDream?: T;
  emotionalOutcome?: T;
  styleDirection?: T;
  locationPreferences?:
    | T
    | {
        preferredCity?: T;
        preferredRegion?: T;
        radiusMiles?: T;
        locationNotes?: T;
      };
  venue?: T;
  vendors?: T;
  menuConcept?: T;
  packageOptions?: T;
  proposal?: T;
  event?: T;
  profitGuardrails?:
    | T
    | {
        targetMargin?: T;
        minimumMargin?: T;
        estimatedBudget?: T;
        internalCostCap?: T;
      };
  systemNotes?: T;
  vision?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendor-partners_select".
 */
export interface VendorPartnersSelect<T extends boolean = true> {
  businessName?: T;
  vendorType?: T;
  contactName?: T;
  email?: T;
  phone?: T;
  website?: T;
  instagram?: T;
  serviceRegion?: T;
  pricingTier?: T;
  preferredPartner?: T;
  whiteLabelApproved?: T;
  averageSpendRange?: T;
  operationalNotes?: T;
  luxuryFitNotes?: T;
  gallery?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues_select".
 */
export interface VenuesSelect<T extends boolean = true> {
  venueName?: T;
  venueType?: T;
  region?: T;
  address?: T;
  website?: T;
  instagram?: T;
  contactName?: T;
  contactEmail?: T;
  contactPhone?: T;
  guestCapacity?: T;
  pricingTier?: T;
  featured?: T;
  whiteLabelReady?: T;
  venueFeatures?: T;
  preferredVendorPartners?: T;
  internalHospitalityNotes?: T;
  luxuryExperienceNotes?: T;
  gallery?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "package-options_select".
 */
export interface PackageOptionsSelect<T extends boolean = true> {
  packageName?: T;
  client?: T;
  experienceBrief?: T;
  status?: T;
  includedVendors?: T;
  selectedVenue?: T;
  menuConcept?: T;
  clientPrice?: T;
  foodCost?: T;
  vendorCost?: T;
  laborCost?: T;
  travelCost?: T;
  rentalCost?: T;
  totalEstimatedCost?: T;
  estimatedProfit?: T;
  profitMargin?: T;
  marginStatus?: T;
  experienceSummary?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  eventName?: T;
  client?: T;
  packageOption?: T;
  venue?: T;
  eventDate?: T;
  guestCount?: T;
  eventStatus?: T;
  assignedVendors?: T;
  timelineNotes?: T;
  staffNotes?: T;
  clientNotes?: T;
  arrivalInstructions?: T;
  specialMoments?: T;
  gallery?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proposals_select".
 */
export interface ProposalsSelect<T extends boolean = true> {
  proposalTitle?: T;
  client?: T;
  event?: T;
  experienceBrief?: T;
  packageOption?: T;
  proposalStatus?: T;
  proposalSummary?: T;
  experienceVision?: T;
  includedExperiences?:
    | T
    | {
        experienceItem?: T;
        id?: T;
      };
  includedVendors?: T;
  venue?: T;
  menuConcept?: T;
  guestCount?: T;
  eventDate?: T;
  totalInvestment?: T;
  depositRequired?: T;
  finalBalance?: T;
  internalProjectedProfit?: T;
  proposalPdf?: T;
  signatureReceived?: T;
  depositPaid?: T;
  clientFeedback?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  brand?: T;
  taskTitle?: T;
  status?: T;
  priority?: T;
  taskType?: T;
  relatedClient?: T;
  relatedInquiry?: T;
  relatedExperience?: T;
  relatedEvent?: T;
  assignedTo?: T;
  dueDate?: T;
  automationEligible?: T;
  generatedBySystem?: T;
  estimatedRevenueImpact?: T;
  notes?: T;
  internalOperationsNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-concepts_select".
 */
export interface MenuConceptsSelect<T extends boolean = true> {
  menuTitle?: T;
  cuisineStyle?: T;
  serviceStyle?: T;
  sampleCourses?:
    | T
    | {
        courseName?: T;
        description?: T;
        id?: T;
      };
  signatureMoments?:
    | T
    | {
        momentTitle?: T;
        momentDescription?: T;
        id?: T;
      };
  winePairingNotes?: T;
  seasonality?: T;
  estimatedFoodCost?: T;
  suggestedClientPrice?: T;
  luxuryTier?: T;
  chefNotes?: T;
  internalMarginNotes?: T;
  gallery?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes_select".
 */
export interface RecipesSelect<T extends boolean = true> {
  name?: T;
  shortDescription?: T;
  category?: T;
  cuisine?: T;
  course?: T;
  dietaryTags?: T;
  allergenTags?: T;
  yieldQuantity?: T;
  yieldUnit?: T;
  prepTimeMinutes?: T;
  cookTimeMinutes?: T;
  ingredients?:
    | T
    | {
        quantity?: T;
        unit?: T;
        ingredient?: T;
        preparationNote?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        instruction?: T;
        id?: T;
      };
  chefNotes?: T;
  platingNotes?: T;
  storageNotes?: T;
  internalCostNotes?: T;
  featuredImage?: T;
  status?: T;
  visibility?: T;
  slug?: T;
  publicTitle?: T;
  publicSummary?: T;
  heroImage?: T;
  chefIntroduction?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  internalName?: T;
  client?: T;
  inquiry?: T;
  event?: T;
  occasionTitle?: T;
  serviceDate?: T;
  guestCount?: T;
  introductoryMessage?: T;
  sections?:
    | T
    | {
        sectionName?: T;
        items?:
          | T
          | {
              recipe?: T;
              clientTitle?: T;
              clientDescription?: T;
              showDietary?: T;
              dietaryDisplay?: T;
              allergenDisplay?: T;
              internalItemNotes?: T;
              id?: T;
            };
        id?: T;
      };
  pricingPresentation?: T;
  displayInvestment?: T;
  internalNotes?: T;
  status?: T;
  version?: T;
  sentAt?: T;
  approvedAt?: T;
  revisionHistory?:
    | T
    | {
        version?: T;
        snapshotAt?: T;
        reason?: T;
        snapshotJson?: T;
        id?: T;
      };
  reviewTokenHash?: T;
  reviewTokenExpiresAt?: T;
  reviewTokenRevokedAt?: T;
  reviewTokenCreatedAt?: T;
  reviews?:
    | T
    | {
        action?: T;
        comment?: T;
        submittedAt?: T;
        menuVersion?: T;
        clientKeyHint?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dietary-notes_select".
 */
export interface DietaryNotesSelect<T extends boolean = true> {
  guestName?: T;
  client?: T;
  restrictionType?: T;
  severity?: T;
  favoriteIngredients?: T;
  ingredientsToAvoid?: T;
  luxuryPreferenceNotes?: T;
  specialNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  clientName?: T;
  experienceType?: T;
  testimonial?: T;
  rating?: T;
  featured?: T;
  featuredQuote?: T;
  eventGallery?: T;
  clientPhoto?: T;
  venue?: T;
  location?: T;
  luxuryExperienceNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}